#!/bin/bash

if [ $# -lt 2 ]
then
	echo
	echo "usage: makecommand Get-Some-Stuff fooMethods";
	echo
	echo "    where 'Get-Some-Stuff' is a capitalized version of the command filename...";
	echo "    and 'fooMethods' is the name of the proper API 'module'.";
	exit;
fi

in=`echo $1`
in_lower=`echo $in | tr A-Z a-z`

COMMANDFILENAME="cato-$in_lower"
CLASS=`echo $in_lower | sed 's/-//g'`
METHOD=`echo $in | sed 's/-//g'`
API=`echo $in_lower | sed 's/-/_/g'`
MODULE=`echo $2`

echo COMMAND FILE: $COMMANDFILENAME
echo CLASS: $CLASS
echo METHOD: $METHOD
echo MODULE: $MODULE
echo API CALL: $API



# the command file
sed -e "s/~CLASS~/$CLASS/g" bin/command-template > bin/$COMMANDFILENAME
sed -i "" "s/~METHOD~/$METHOD/g" bin/$COMMANDFILENAME
chmod 755 bin/$COMMANDFILENAME


# the source file
sed -e "s/~METHOD~/$METHOD/g" catoclient/commands/commandtemplate.py > catoclient/commands/$CLASS.py
sed -i "" "s/~MODULE~/$MODULE/g" catoclient/commands/$CLASS.py
sed -i "" "s/~APICALL~/$API/g" catoclient/commands/$CLASS.py

