#########################################################################
#
# Copyright 2013 Cloud Sidekick
# __________________
#
#  All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Cloud Sidekick and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Cloud Sidekick
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Cloud Sidekick.
#
#########################################################################

import commands.catocommand
from commands.param import Param


class InitiatePipeline(commands.catocommand.CatoCommand):

    Description = """Creates a new Release Candidate in a Pipeline with matching 'key' information.

Returns a Release Candidate Object."""

    API = 'initiate_pipeline'
    Examples = ''''''
    Options = [Param(name='pipeline', short_name='p', long_name='pipeline',
                     optional=False, ptype='string',
                     doc='Value can be either a Pipeline ID or Name.'),
               Param(name='story', short_name='s', long_name='story',
                     optional=False, ptype='string',
                     doc='Story identifier for this Release Candidate.'),
               Param(name='project', short_name='r', long_name='project',
                     optional=True, ptype='string',
                     doc='A specific Project identifier.'),
               Param(name='rc_name', short_name='n', long_name='rc_name',
                     optional=True, ptype='string',
                     doc='An explicit name for the new Release Candidate. (Autogenerated if omitted.)'),
               Param(name='details', short_name='d', long_name='details',
                     optional=True, ptype='string',
                     doc='A JSON object with additional details for the Release Candidate.')
               ]

    def main(self):
        results = self.call_api(self.API, ['pipeline', 'story', 'project', 'rc_name', 'details'])
        print(results)
